name: Image Downloader

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  download-images:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip

      - name: Install Playwright
        run: |
          pip install playwright
          playwright install chromium

      - name: Install Python Dependencies
        run: |
          pip install aiohttp
          pip install playwright
          pip install pyzipper

      - name: Extract Protected Script
        run: |
          # Extract the password-protected zip
          ZIP_PASSWORD="${{ secrets.ZIP_PASSWORD }}" python extract_script.py

      - name: Run Image Downloader
        run: python image_downloader.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add images directory if it exists
          if [ -d "images" ]; then
            git add images/
          fi
          
          # Add summary file if it exists
          if [ -f "image-download-summary.json" ]; then
            git add image-download-summary.json
          fi
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "📸 Auto update images - $(date '+%Y-%m-%d %H:%M:%S')"
          fi

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

permissions:
  contents: write 
